id: P004231
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG3383
  title: དབོན་སྟོད་མཁྱེན་རབ་ཀྱི་རྣམ་ཐར་དང་གསུང་གཅེས་བཏུས།
  author: ''
  volumes:
    4b93c4a0da5044adad9d955ae2bd7731:
      image_group_id: I1KG3964
      title: ''
      volume_number: 1
      total_pages: 200
      base_file: v001.txt
